The line graph component.
ChrisPastor/healthy-competition-website pull request #11
Opened 2020-11-12 00:29 UTC by ellammiller

2020-11-12 00:37 UTC, ChrisPastor requested changes

2020-11-12 00:37 UTC, ChrisPastor commented on frontend/src/common/Graph.tsx
> +var CanvasJSChart = CanvasJSReact.CanvasJSChart;
Use the primereact chart instead of canvas.

2020-11-14 21:21 UTC, ChrisPastor approved these changes

2020-11-15 00:18 UTC, rcharl6 approved these changes

2020-11-15 00:39 UTC, ChrisPastor commented on frontend/src/common/Graph.tsx
> +);
modify this to a functional component --> 
`const ProgressGraph = () => {
return (<div...)
}`

2020-11-17 01:46 UTC, ChrisPastor approved these changes

2020-11-17 01:46 UTC, merged